version: '3.0'

services:
  web:
    container_name: ModbusIoT
    restart: always
    build: .
    network_mode: "host"
    environment:
      - LANG=en_US.UTF-8
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0