# List must contain value in this format >>> [SLAVE_ID, REG_ADDRESS, DATA_TYPE, BYTEORDER, BYTESWAP, FUNCTION_CODE]
# SLAVE_ID: 1
# INT_VAL01: [1, 1,"int16","N","N", 3]
# INT_VAL02: [1, 2, "int16","N","N", 3]
# INT_VAL03: [1, 3, "int16","N","N", 3]
# INT_VAL04: [1, 4, "int16","N","N", 3]
# INT_VAL05: [1, 5, "int16", "N", "N", 3]
# INT_VAL06: [1, 6,"int16","N","N", 3]
# INT_VAL07: [1, 7, "int16","N","N", 3]
# INT_VAL08: [1, 8, "int16","N","N", 3]
# INT_VAL09: [1, 9, "int16","N","N", 3]
# INT_VAL10: [1, 10, "int16", "N", "N", 3]
# INT_VAL11: [1, 11,"int16","N","N", 3]
# INT_VAL12: [1, 12, "int16","N","N", 3]
# INT_VAL13: [1, 13, "int16","N","N", 3]
# INT_VAL14: [1, 14, "int16","N","N", 3]
# INT_VAL15: [1, 15, "int16", "N", "N", 3]
# FLOAT_VAL01: [1, 16, "float32", "big", "N", 3]  # AB CD
# FLOAT_VAL02: [1, 18, "float32", "big", "byte-swap", 3] # BA DC
# FLOAT_VAL03: [1, 20, "float32", "little", "N", 3] # DC BA
# FLOAT_VAL04: [1, 22, "float32", "little", "byte-swap", 3] # CD AB
# FLOAT_VAL05: [1, 24, "float32", "big", "N", 3]  # AB CD
# FLOAT_VAL06: [1, 26, "float32", "big", "byte-swap", 3] # BA DC
# FLOAT_VAL07: [1, 28, "float32", "little", "N", 3] # DC BA
# FLOAT_VAL08: [1, 30, "float32", "little", "byte-swap", 3] # CD AB
# FLOAT_VAL09: [1, 32, "float32", "big", "N", 3] # AB CD
# FLOAT_VAL10: [1, 34, "float32", "big", "byte-swap", 3] # BA DC
# FLOAT_VAL11: [1, 36, "float32", "little", "N", 3] # DC BA
# FLOAT_VAL12: [1, 38, "float32", "little", "byte-swap", 3] # CD AB
# FLOAT_VAL13: [1, 40, "float32", "big", "N", 3] # AB CD
# FLOAT_VAL14: [1, 42, "float32", "big", "byte-swap", 3] # BA DC
# FLOAT_VAL15: [1, 44, "float32", "little", "N", 3] # DC BA
OilInWater: [1, 1, "float32", "big", "byte-swap", 4]
PH: [1, 3, "float32", "big", "byte-swap", 4]
TEMP: [1, 5, "float32", "big", "byte-swap", 4]
# O2: [1, 20, "float32", "little", "N", 4]